// Generated by CoffeeScript 1.6.2
window.dR = function(fn) {
  var d;

  d = document;
  if (/complete|loaded|interactive/.test(d.readyState)) {
    return fn;
  } else {
    if (d.addEventListener) {
      return d.addEventListener("DOMContentLoaded", fn, false);
    } else if (d.attachEvent) {
      return d.attachEvent("onDOMContentLoaded", fn);
    } else {
      return d["onDOMContentLoaded"] = fn;
    }
  }
};
